<?php

namespace Dxw\CIDR;

class AddressBase
{
    private $address;

    public static function Make(string $address): \Dxw\Result\Result
    {
        // I hate to suppress warnings, but there's no other way to disable
        // warnings generated by inet_pton, and we are handling it
        $_address = @inet_pton($address);
        if ($_address === false) {
            return \Dxw\Result\Result::err('inet_pton error: unrecognised address');
        }

        return \Dxw\Result\Result::ok(new static($_address));
    }

    private function __construct(string $address)
    {
        $this->address = $address;
    }

    public function __toString(): string
    {
        return inet_ntop($this->address);
    }

    public function getBinary(): \phpseclib\Math\BigInteger
    {
        return new \phpseclib\Math\BigInteger($this->address, 256);
    }
}
